apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: com.dev.label-add
webhooks:
- name: com.dev.label-add
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: default
      name: label-add
      path: "/"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHekNDQWdPZ0F3SUJBZ0lVWjcyaXAyRDl0aXRuNGw1ZHJtZUdaby9mZ2Z3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hERWFNQmdHQTFVRUF3d1JUR0ZpWld3Z1FXUmtJRmRsWW1odmIyc3dJQmNOTWpNd01qSXpNVFUxTVRJNQpXaGdQTWpFeU16QXhNekF4TlRVeE1qbGFNQnd4R2pBWUJnTlZCQU1NRVV4aFltVnNJRUZrWkNCWFpXSm9iMjlyCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBM2pKVHhPdHFtN1hoUEdoNGNQcEIKckhNZTZoSFJHY3BlYjh0L0h1bjZYby9aMmxZd29mckdrWDlJS2ZQMTVzNENMdTRxeUVqME14WUNVdUhTanpFMApWMU9wYTV1d3cvTlJLMFg0WU5iRFNpUWtTNThyMjU3WXlNM3JhUlhVWTRwalVtVnV6MWlNN3N2a0wxajQxbnVuCisvU2x4YzVhVnBabndhMmRSQWkvbDJtL3BxZEdHTkhoM05Xamd2K0wxdHY0Mld6SkJFVjl3NkZPejhMbnQzRWUKSGsvSWw0OHBWRVVNYnd6VkFOd2FCZXBNRmFuT05xcjVVSzNLcHVsTVgxL0xPRFAwaGYxZjhjeUY0WjBxSzgwYgo0VWVKajE4ZWo2ajVmWXNtaXlIQXdIOHhGSmN2YXFmMUcwdFRvUFdHaTJMWU1kaVp2cEp2OFNYakdDWTh0Y2FsCi93SURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVVWZnBIYzVsc09Jb2pHMmRSMHdUUWpJREk1dWt3SHdZRFZSMGoKQkJnd0ZvQVVWZnBIYzVsc09Jb2pHMmRSMHdUUWpJREk1dWt3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcQpoa2lHOXcwQkFRc0ZBQU9DQVFFQWlLdkUvR243WTFEMVQwQkxSMXhzelFnTis4dnJpTklxbVQ0ZXU2WjFraEdhCkg1R3QxSml4V3JBNjdoWTB0Tk5RbEkyNVFaK1lpVTIxZHQrRTVqNmtHQXgvZHBQL3BqZUY4dTFScEFieXV3dGsKZ0kvL1lzMUI3SmxtRGNySkxyNzBoSGw5c1pPaEs5bjMyQ0tTNThvS2UweVk3RTJGUW5EcnQrbEZIY0xGYitOVwpqV1Q2MlQ3bFg4WHhOVDRlRzE2VXVRcnlxNWhvY3JkQVNhRzk4QVNGNzVESk1BODFyeWJidEdjbm5BcWprRGhUCmg5RFdiaitEZlN2Y2VRVmNQWjJvTExxTkJFcVpLd0dYOHdvZlNjK2UwME5oak9yc1loOEFRZXZVYzZHTnFrZHEKQVJrbTFMMEFhamhJbm4wa2IyTXRUTno3NUZnS2czQnpjdUkrSXNUZ0FRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  admissionReviewVersions: ["v1"]
  sideEffects: None
